log:
  # Valid levels are:
  # - None/0
  # - Info/1
  # - Debug/2
  level: Debug

  # Set the location for logs to appear, default is the terminal
  location: log.txt

# Enables the use of scripts to run during startup
# Can be inline commands or define a file with the startup script
# startup: |
#   FILE
#   (file path).txt

startup: |
  f:x->2x
  g:y->2f(y)

keywords:
  QUIT: "quit" # Input string to exit the program
  ENV: "env" # Input string to show the environment
  RELOAD: "reload" # Input string to reload the config
