name: Build
run-name: Build ${{ github.ref_name }}
on: workflow_dispatch
jobs:
  build-mac:
    runs-on: macos-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: brew install cmake pkg-config libyaml

      - name: Configure CMake
        run: |
          export PKG_CONFIG_PATH=$(brew --prefix libyaml)/lib/pkgconfig
          cmake -B build -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXE_LINKER_FLAGS="-static"

      - name: Build MacOS
        run: cmake --build build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: algebra-${{ runner.os }} # This names it algebra-macOS, algebra-Windows, etc.
          path: build/algebra*

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup MSYS2
        uses: msys2/setup-msys2@v2
        with:
          update: true
          install: >-
            mingw-w64-x86_64-libyaml
            mingw-w64-x86_64-pkg-config
            mingw-w64-x86_64-cmake
            mingw-w64-x86_64-gcc
            mingw-w64-x86_64-make

      - name: Configure and Build
        # This 'shell: msys2 {0}' is the secret sauce. 
        # It runs the commands inside the MSYS2 environment where pkg-config lives.
        shell: msys2 {0}
        run: |
          cmake -B build -G "MinGW Makefiles" -DCMAKE_BUILD_TYPE=Release -DCMAKE_EXE_LINKER_FLAGS="-static"
          cmake --build build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: algebra-Windows
          # Using a wildcard to catch .exe on Windows
          path: build/algebra*

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: |
          sudo apt update
          sudo apt install -y cmake libyaml-dev
        
      - name: Configure CMake
        run: cmake -B build -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: algebra-${{ runner.os }} # This names it algebra-macOS, algebra-Windows, etc.
          path: build/algebra*
